- project:
    templates:
      - check-requirements
      - openstack-python-jobs
      - openstack-python35-jobs
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/nova
        - openstack-tox-py27:
            required-projects:
              - openstack/nova
        - openstack-tox-py35:
            required-projects:
              - openstack/nova
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/nova
        - openstack-tox-py27:
            required-projects:
              - openstack/nova
        - openstack-tox-py35:
            required-projects:
              - openstack/nova
